### ISSUE TITLE
Facebook window is too small

### ISSUE THREAD

**Issue by rodrigoprimo** [rodrigoprimo/social-connect#66]
The Facebook approval window displays the following message: "Your popup is too small to display this page. Please enlarge it to proceed".

**Comment by hazapollos** [comment]
Hi there, this problem is still happening Jan 6, 2015
Where can I modify the size of the pop up on the code?

Thanks
![image](https://cloud.githubusercontent.com/assets/11987642/12165190/b9687880-b4d0-11e5-8376-4799ef3bd6eb.png)

**Comment by hazapollos** [comment]
![image](https://cloud.githubusercontent.com/assets/11987642/12165269/419486b8-b4d1-11e5-8bff-9df363705fd5.png)
