### ISSUE TITLE
maintenance, support and future development

### ISSUE THREAD

**Issue by adispiac** [rodrigoprimo/social-connect#80]
Hi Rodrigo,

I would be interested in taking over the development and maintenance of your Social Connect plugin.
Over at [Cozmoslabs](http://www.cozmoslabs.com) we're a team of 8, working exclusively with WordPress.

Would love to discuss how do you see the transition happening. Please get in touch [here](mailto:adrian@cozmoslabs.com) to talk more.

Thank you,

**Comment by rodrigoprimo** [comment]
Thanks for your interest. I just replied your e-mail and I'm closing this issue.
